; php-fpm.custom.conf

[www]  ; Pool name

; Increase the maximum execution time of each request
; Matches or exceeds the max_execution_time in php.ini
request_terminate_timeout = 300s  ; Adjust as needed

pm = ondemand
pm.max_children = 24
pm.process_idle_timeout = 10s


; Set the memory limit for each child process
; Ensures that each process has enough memory to handle large uploads
php_admin_value[memory_limit] = 512M  ; Adjust as needed

; Set the maximum allowed size for uploaded files
php_admin_value[upload_max_filesize] = 20M  ; Adjust as needed

; Set the maximum amount of POST data allowed
php_admin_value[post_max_size] = 1G  ; Adjust as needed

; Set the maximum execution time for scripts
php_admin_value[max_execution_time] = 300  ; Adjust as needed

; Set the maximum input parsing time for scripts
php_admin_value[max_input_time] = 300  ; Adjust as needed

