title: Default
options:
  preview: "{{ page.frontendUrl }}"

tabs:
  main:
    columns:
      main:
        width: 2/3
        sections:
          pageHeader:
            extends: sections/page-header
          fields:
            type: fields
            fields:
              layout:
                type: layout
                fieldsets:
                  - sectionTitle
                  - heading
                  - text
                  - image
                  - gallery
                  - quote
                  - video
                  - buttons
                  - gap
      files:
        width: 1/3
        sections:
          files:
            type: files
