options:
  preview: "{{ site.frontendUrl }}"
columns:
  - width: 1/2
    sections:
      data:
        type: pages
        headline:
          en: Data
          de: Daten
        help: This section represents a database for the Kirby API.
        query: page('data').children
        create: false
      fields:
        type: fields
        fields:
          menuItems:
            type: pages
            headline:
              en: Menu Items
              nl: Menu Items
          footerNavigation:
            type: pages
            headline:
              en: Footer Navigation
              nl: Footer Navigatie
          footerSecondaryNavigation:
            type: pages
            headline:
              en: Footer Secondary Navigation
              nl: Footer Secundaire Navigatie
          anbiLink:
            type: files
            headline:
              en: ANBI File
              nl: ANBI File
            multiple: false
          contact:
            type: object
            headline:
              en: Contact
              nl: Contact
            fields:
              email:
                type: email
                headline:
                  en: Email
                  nl: E-mail
              phone:
                type: tel
                headline:
                  en: Phone
                  nl: Telefoon
              instagram:
                type: url
                headline:
                  en: Instagram
                  nl: Instagram
              linkedin:
                type: url
                headline:
                  en: LinkedIn
                  nl: LinkedIn
              youtube:
                type: url
                headline:
                  en: YouTube
                  nl: YouTube

  - width: 1/2
    sections:
      programmes:
        type: pages
        headline:
          en: Programmes
          de: Programme
        help: This section represents the programmes for the Kirby site.
        query: site.index.template('programmes')
      pages:
        type: pages
        headline:
          en: Pages
          de: Paginas
        help: This section represents the pages for the Kirby site.
        query: site.childrenAndDrafts.filterBy('intendedTemplate', 'not in', ['data', 'programmes'])
