name: Deploy to Vimexx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vimexx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: web0161.zxcs.nl
          username: u181643p258906
          key: ${{ secrets.VIMEXX_SSH_KEY }}
          script: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /domains/robinfoodcoalition.nl/public_html/panel
            if [ ! -d ".git" ]; then
              git clone git@github.com:jpleass/rfc-kirby.git .
            else
              git pull origin main
            fi
