name: Deploy to Opalstack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code on Opalstack server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: opal11.opalstack.com
          username: jpleass
          key: ${{ secrets.OPALSTACK_SSH_KEY }}
          script: |
            cd /home/jpleass/apps/rfc-kirby/
            git pull origin main
